'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="datasave")>  _
Partial Public Class DataClasses_PIECEDATASAVEDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "可扩展性方法定义"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.逆转测试.My.MySettings.Default.datasaveConnectionString2, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property piecedatasave() As System.Data.Linq.Table(Of piecedatasave)
		Get
			Return Me.GetTable(Of piecedatasave)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.piecedatasave")>  _
Partial Public Class piecedatasave
	
	Private _编号 As String
	
	Private _日期 As String
	
	Private _工件类别 As String
	
	Private _条码 As String
	
	Private _结果 As String
	
	Private _右反驱力最大值 As String
	
	Private _右反驱力最小值 As String
	
	Private _右反驱力波动量 As String
	
	Private _右反驱力平均值 As String
	
	Private _右反驱动位移 As String
	
	Private _左反驱力最大值 As String
	
	Private _左反驱力最小值 As String
	
	Private _左反驱力波动量 As String
	
	Private _左反驱力平均值 As String
	
	Private _左反驱动位移 As String
	
	Private _左右波动量差值 As String
	
	Private _上拉齿条径向间隙 As String
	
	Private _上拉齿条径向力 As String
	
	Private _下拉齿条径向间隙 As String
	
	Private _下拉齿条径向力 As String
	
	Private _左右反驱力平均值差值 As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_编号", DbType:="NVarChar(255)")>  _
	Public Property 编号() As String
		Get
			Return Me._编号
		End Get
		Set
			If (String.Equals(Me._编号, value) = false) Then
				Me._编号 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_日期", DbType:="NVarChar(255)")>  _
	Public Property 日期() As String
		Get
			Return Me._日期
		End Get
		Set
			If (String.Equals(Me._日期, value) = false) Then
				Me._日期 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_工件类别", DbType:="NVarChar(255)")>  _
	Public Property 工件类别() As String
		Get
			Return Me._工件类别
		End Get
		Set
			If (String.Equals(Me._工件类别, value) = false) Then
				Me._工件类别 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_条码", DbType:="NVarChar(255)")>  _
	Public Property 条码() As String
		Get
			Return Me._条码
		End Get
		Set
			If (String.Equals(Me._条码, value) = false) Then
				Me._条码 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_结果", DbType:="NVarChar(255)")>  _
	Public Property 结果() As String
		Get
			Return Me._结果
		End Get
		Set
			If (String.Equals(Me._结果, value) = false) Then
				Me._结果 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_右反驱力最大值", DbType:="NVarChar(255)")>  _
	Public Property 右反驱力最大值() As String
		Get
			Return Me._右反驱力最大值
		End Get
		Set
			If (String.Equals(Me._右反驱力最大值, value) = false) Then
				Me._右反驱力最大值 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_右反驱力最小值", DbType:="NVarChar(255)")>  _
	Public Property 右反驱力最小值() As String
		Get
			Return Me._右反驱力最小值
		End Get
		Set
			If (String.Equals(Me._右反驱力最小值, value) = false) Then
				Me._右反驱力最小值 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_右反驱力波动量", DbType:="NVarChar(255)")>  _
	Public Property 右反驱力波动量() As String
		Get
			Return Me._右反驱力波动量
		End Get
		Set
			If (String.Equals(Me._右反驱力波动量, value) = false) Then
				Me._右反驱力波动量 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_右反驱力平均值", DbType:="NVarChar(255)")>  _
	Public Property 右反驱力平均值() As String
		Get
			Return Me._右反驱力平均值
		End Get
		Set
			If (String.Equals(Me._右反驱力平均值, value) = false) Then
				Me._右反驱力平均值 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_右反驱动位移", DbType:="NVarChar(255)")>  _
	Public Property 右反驱动位移() As String
		Get
			Return Me._右反驱动位移
		End Get
		Set
			If (String.Equals(Me._右反驱动位移, value) = false) Then
				Me._右反驱动位移 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_左反驱力最大值", DbType:="NVarChar(255)")>  _
	Public Property 左反驱力最大值() As String
		Get
			Return Me._左反驱力最大值
		End Get
		Set
			If (String.Equals(Me._左反驱力最大值, value) = false) Then
				Me._左反驱力最大值 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_左反驱力最小值", DbType:="NVarChar(255)")>  _
	Public Property 左反驱力最小值() As String
		Get
			Return Me._左反驱力最小值
		End Get
		Set
			If (String.Equals(Me._左反驱力最小值, value) = false) Then
				Me._左反驱力最小值 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_左反驱力波动量", DbType:="NVarChar(255)")>  _
	Public Property 左反驱力波动量() As String
		Get
			Return Me._左反驱力波动量
		End Get
		Set
			If (String.Equals(Me._左反驱力波动量, value) = false) Then
				Me._左反驱力波动量 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_左反驱力平均值", DbType:="NVarChar(255)")>  _
	Public Property 左反驱力平均值() As String
		Get
			Return Me._左反驱力平均值
		End Get
		Set
			If (String.Equals(Me._左反驱力平均值, value) = false) Then
				Me._左反驱力平均值 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_左反驱动位移", DbType:="NVarChar(255)")>  _
	Public Property 左反驱动位移() As String
		Get
			Return Me._左反驱动位移
		End Get
		Set
			If (String.Equals(Me._左反驱动位移, value) = false) Then
				Me._左反驱动位移 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_左右波动量差值", DbType:="NVarChar(255)")>  _
	Public Property 左右波动量差值() As String
		Get
			Return Me._左右波动量差值
		End Get
		Set
			If (String.Equals(Me._左右波动量差值, value) = false) Then
				Me._左右波动量差值 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_上拉齿条径向间隙", DbType:="NVarChar(255)")>  _
	Public Property 上拉齿条径向间隙() As String
		Get
			Return Me._上拉齿条径向间隙
		End Get
		Set
			If (String.Equals(Me._上拉齿条径向间隙, value) = false) Then
				Me._上拉齿条径向间隙 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_上拉齿条径向力", DbType:="NVarChar(255)")>  _
	Public Property 上拉齿条径向力() As String
		Get
			Return Me._上拉齿条径向力
		End Get
		Set
			If (String.Equals(Me._上拉齿条径向力, value) = false) Then
				Me._上拉齿条径向力 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_下拉齿条径向间隙", DbType:="NVarChar(255)")>  _
	Public Property 下拉齿条径向间隙() As String
		Get
			Return Me._下拉齿条径向间隙
		End Get
		Set
			If (String.Equals(Me._下拉齿条径向间隙, value) = false) Then
				Me._下拉齿条径向间隙 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_下拉齿条径向力", DbType:="NVarChar(255)")>  _
	Public Property 下拉齿条径向力() As String
		Get
			Return Me._下拉齿条径向力
		End Get
		Set
			If (String.Equals(Me._下拉齿条径向力, value) = false) Then
				Me._下拉齿条径向力 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_左右反驱力平均值差值", DbType:="NVarChar(255)")>  _
	Public Property 左右反驱力平均值差值() As String
		Get
			Return Me._左右反驱力平均值差值
		End Get
		Set
			If (String.Equals(Me._左右反驱力平均值差值, value) = false) Then
				Me._左右反驱力平均值差值 = value
			End If
		End Set
	End Property
End Class
